// The deprecated single-phase execution path (transaction-binding and the
// executors/{safe,waap,unsigned} classes) is deliberately NOT exported. It
// stamps `validated: true` on caller-supplied calldata. It remains requirable
// by path for the migration, gated on GAVEL_ALLOW_DEPRECATED_EXECUTORS=1.
module.exports = {
  ...require("./src/schema/governance"),
  ...require("./src/governance/lifecycle"),
  ...require("./src/schema/execution"),
  ...require("./src/schema/intent"),
  ...require("./src/intent/vote-intent"),
  ...require("./src/intent/execution-intent"),
  ...require("./src/intent/validated"),
  ...require("./src/intent/from-preparation"),
  ...require("./src/profile/build"),
  ...require("./src/profile/onboarding"),
  ...require("./src/predict/predict"),
  ...require("./src/backtest/calibration"),
  ...require("./src/backtest/run"),
  ...require("./src/operations/failure"),
  ...require("./src/execution/modes"),
  ...require("./src/execution/lifecycle"),
  ...require("./src/execution/records"),
  ...require("./src/execution/events"),
  ...require("./src/execution/adapter"),
  ...require("./src/execution/replay"),
  ...require("./src/execution/engine"),
  ...require("./src/execution/profile"),
  ...require("./src/execution/readiness"),
  ...require("./src/execution/identity/signing"),
  ...require("./src/execution/identity/roles"),
  ...require("./src/execution/providers/safe-proposal"),
  ...require("./src/execution/executors/safe-supervised"),
  ...require("./src/execution/executors/waap-autonomous"),
  ...require("./src/dao/registry"),
  ...require("./src/dao/contract"),
  ...require("./src/dao/catalog"),
  ...require("./src/dao/proposal-ref"),
  ...require("./src/config/secrets"),
  ...require("./src/config/schema"),
  ...require("./src/config/migrate"),
  ...require("./src/config/store"),
  ...require("./src/wallet/provider"),
  ...require("./src/wallet/providers"),
  ...require("./src/readiness/gavel-readiness"),
  ...require("./src/onboarding/setup-wizard"),
  ...require("./src/view/inbox"),
  ...require("./src/execution/executors/interactive-wallet"),
  ...require("./src/storage/private-state"),
  ...require("./src/rpc/block-range"),
};
